name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      run: yarn --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Type checks
      run: yarn type
    
    - name: Tests
      run: yarn test
